name: Update trending topic
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *'

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip install requests
      - run: pip install beautifulsoup4
      - run: python src/main.py
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public